module.exports = [
  {
    firstName: 'Valerie',
    lastName: 'Frizzle',
    email: 'vfrizzle@msb.com',
    username: 'vfrizzle',
    password: 'password1',
    position: 'Instructor',
    image: null,
  }, {
    firstName: 'Keesha',
    lastName: 'Franklin',
    email: 'kfranklin@msb.com',
    username: 'kfranklin',
    password: 'password2',
    position: 'Student',
    image: null,
  }, {
    firstName: 'Phoebe',
    lastName: 'Terese',
    email: 'pterese@msb.com',
    username: 'pterese',
    password: 'password3',
    position: 'Student',
    image: null,
  }, {
    firstName: 'Ralphi',
    lastName: 'Tennelli',
    email: 'rtennelli@msb.com',
    username: 'rtennelli',
    password: 'password4',
    position: 'Student',
    image: null,
  },
];
