module.exports = [
  {
    firstName: 'Gabriel',
    lastName: 'Frizzle',
    email: 'gfrizzle@msb.com',
    username: 'gfrizzle',
    password: 'password1',
    position: 'Instructor',
    image: null,
  }, {
    firstName: 'Samantha',
    lastName: 'Bretous',
    email: 'sBretous@msb.com',
    username: 'sam',
    password: 'password2',
    position: 'Student',
    image: null,
  }, {
    firstName: 'joshua',
    lastName: 'fermin',
    email: 'jfermin@msb.com',
    username: 'joshua',
    password: 'password3',
    position: 'Student',
    image: null,
  }, {
    firstName: 'Melanie',
    lastName: 'Williams',
    email: 'mWilliams@msb.com',
    username: 'mel',
    password: 'password4',
    position: 'Student',
    image: null,
  },
];
