module.exports = [{
  zipFile: 'pede_lobortis_ligula.js',
  grade: 12,
  assignmentId: 1,
}, {
  zipFile: 'in.html',
  grade: 51,
  assignmentId: 1,
}, {
  zipFile: 'velit_vivamus.js',
  grade: 37,
  assignmentId: 1,
}, {
  zipFile: 'posuere.js',
  grade: 98,
  assignmentId: 2,
}, {
  zipFile: 'maecenas_ut_massa.css',
  grade: 36,
  assignmentId: 2,
}, {
  zipFile: 'diam_cras.js',
  grade: 63,
  assignmentId: 2,
}, {
  zipFile: 'mi_integer.js',
  grade: 22,
  assignmentId: 3,
}, {
  zipFile: 'ut_nulla.js',
  grade: 42,
  assignmentId: 3,
}, {
  zipFile: 'auctor.js',
  grade: 56,
  assignmentId: 3,
}, {
  zipFile: 'venenatis.java',
  grade: 58,
  assignmentId: 4,
}, {
  zipFile: 'cras.js',
  grade: 3,
  assignmentId: 4,
}, {
  zipFile: 'a_odio.css',
  grade: 99,
  assignmentId: 5,
}];
